<a href="https://colab.research.google.com/github/JakeOh/202505_BD50/blob/main/lab_da/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 고급기능

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# np.ndarray 속성

In [2]:
arr = np.ones(shape=(2, 3))

In [3]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr.shape  # shape 속성: 배열의 각 축(axis)을 따라서 있는 원소의 개수들의 tuple.

(2, 3)

In [5]:
arr.dtype  # dtype 속성: 배열 원소의 데이터 타입.

dtype('float64')

In [6]:
arr.size  # size 속성: 배열의 모든 원소 개수.

6

In [7]:
arr.ndim  # ndim: 배열의 차원(dimension). 배열의 축(axis)의 개수.

2

In [8]:
arr = np.arange(10)  # 0 이상 10 미만의 (10개의) 정수들로 이루어진 배열.

In [9]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print('dtyp:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtyp: int64
ndim: 1
shape: (10,)
size: 10


In [11]:
arr = np.arange(1, 25).reshape((2, 3, 4))

In [12]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
print('dtyp:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtyp: int64
ndim: 3
shape: (2, 3, 4)
size: 24


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [14]:
print(arr)  #> 3d array(3차원 배열)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [15]:
print(arr[0])  #> 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(arr[0, 0])  #> 1d array

[1 2 3 4]


In [17]:
print(arr[0][0])

[1 2 3 4]


In [18]:
print(arr[0, 0, 0])  #> int -> 스칼라(scalar)

1


In [19]:
print(arr[0][0][0])

1


*   Python list 인덱스 사용 방법:
    *   `list[i][j][k]...`
*   NumPy ndarray 인덱스 사용 방법:
    *   `array[i, j, k, ...]`
    *   `array[i][j][k]...`

# Slicing