<a href="https://colab.research.google.com/github/JakeOh/202505_BD50/blob/main/lab_da/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 고급기능

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# np.ndarray 속성

In [2]:
arr = np.ones(shape=(2, 3))

In [3]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr.shape  # shape 속성: 배열의 각 축(axis)을 따라서 있는 원소의 개수들의 tuple.

(2, 3)

In [5]:
arr.dtype  # dtype 속성: 배열 원소의 데이터 타입.

dtype('float64')

In [6]:
arr.size  # size 속성: 배열의 모든 원소 개수.

6

In [7]:
arr.ndim  # ndim: 배열의 차원(dimension). 배열의 축(axis)의 개수.

2

In [8]:
arr = np.arange(10)  # 0 이상 10 미만의 (10개의) 정수들로 이루어진 배열.

In [9]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print('dtyp:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtyp: int64
ndim: 1
shape: (10,)
size: 10


In [11]:
arr = np.arange(1, 25).reshape((2, 3, 4))

In [12]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
print('dtyp:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtyp: int64
ndim: 3
shape: (2, 3, 4)
size: 24


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [14]:
print(arr)  #> 3d array(3차원 배열)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [15]:
print(arr[0])  #> 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(arr[0, 0])  #> 1d array

[1 2 3 4]


In [17]:
print(arr[0][0])

[1 2 3 4]


In [18]:
print(arr[0, 0, 0])  #> int -> 스칼라(scalar)

1


In [19]:
print(arr[0][0][0])

1


*   Python list 인덱스 사용 방법:
    *   `list[i][j][k]...`
*   NumPy ndarray 인덱스 사용 방법:
    *   `array[i, j, k, ...]`
    *   `array[i][j][k]...`

# Slicing

## 1차원 배열의 slicing

In [20]:
np.random.seed(1)
arr = np.random.randint(100, size=10)  # [0, 100) 범위의 정수 난수 10개로 이루어진 1d array.

In [21]:
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [22]:
print(arr[1:5])

[12 72  9 75]


In [23]:
print(arr[:3])  #> 시작 인덱스 0은 생략 가능

[37 12 72]


In [24]:
print(arr[-3:])  #> 배열의 끝까지 자를 때는 마지막 인덱스는 생략 가능.
# 배열의 끝에서부터 거꾸로 매기는 인덱스는 음수 인덱스.

[64 16  1]


In [26]:
print(arr[0:1])  #> slicing의 결과 -> 배열
print(arr[0])    #> indexing의 결과 -> 원소(스칼라)

[37]
37


## 2차원 배열의 slicing

In [28]:
arr = np.arange(1, 21).reshape((4, 5))

In [29]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [35]:
# 2차원 배열 arr의 첫 2개의 1차원 배열
# print(arr[:2])
print(arr[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [36]:
# 2차원 배열 arr의 마지막 2개의 1차원 배열
# print(arr[-2:])
print(arr[-2:, :])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [38]:
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [41]:
print(arr[1:3][1:4])  # 위쪽 셀의 결과와 비교!

[[11 12 13 14 15]]


## 3차원 배열의 slicing

In [42]:
arr = np.arange(1, 61).reshape((3, 4, 5))

In [43]:
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [44]:
print(arr[:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [45]:
print(arr[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [47]:
# print(arr[:2, :2, :])
print(arr[:2, :2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [48]:
print(arr[:2, :2, :2])

[[[ 1  2]
  [ 6  7]]

 [[21 22]
  [26 27]]]


In [50]:
print(arr[:1, :, :])  #> 결과: 3d array

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [49]:
print(arr[0, :, :])  #> 결과: 2d array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Shape(모양) 변경

*   `np.ndarray.reshape(arg)`
*   `np.ndarray.ravel()`
*   `np.ndarray.flatten()`
*   `np.newaxis` 속성

## reshape

In [51]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [52]:
# arr_1d를 (4, 3) shape의 2d array로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
# reshape 메서드의 아규먼트를 전달할 때 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((4, -1))  #> (4, 3)
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
arr_2d = arr_1d.reshape((-1, 4))  #> (3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
# 2차원 배열 arr_2d를 1차원 배열로 변환.
result = arr_2d.reshape((3 * 4,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [57]:
result = arr_2d.reshape((-1,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [58]:
arr_1d = np.arange(60)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [60]:
# 1차원 배열 arr_1d의 모양을 (3, 4, 5)로 변환
result = arr_1d.reshape((3, 4, -1))  # (3, 4, 5)
print(result)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [61]:
# 1차원 배열 arr_1d의 모양을 (5, 4, 3)로 변환
result = arr_1d.reshape((5, 4, -1))
print(result)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]

 [[48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


## ravel vs flatten

*   flatten
    *   n차원 배열 ndarray를 1차원 배열로 변환한 "복사본"을 리턴.
    *   원본 배열과는 별개의 새로운 배열을 메모리에 만들어서 리턴.
*   ravel
    *   n차원 배열 ndarray를 1차원 배열로 변환한 "뷰(view)"를 리턴.
    *   별개의 새로운 배열을 만드는 것이 아니라, 원본 배열의 모양을 1차원으로 보여줄 뿐.

In [62]:
arr_2d = np.arange(12).reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [63]:
flattened = arr_2d.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [65]:
flattened[0] = 123  #> 1차원 배열 flattened의 첫번째 위치에 새로운 값을 재할당.
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [66]:
print(arr_2d)  # 원본 2차원 배열과는 무관.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [67]:
raveled = arr_2d.ravel()
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [69]:
raveled[0] = 123  # 1차원 배열의 원소를 변경
print(raveled)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [70]:
print(arr_2d)  # 원본 2차원 배열의 값을 변경!

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [71]:
arr = np.arange(1, 6)
print(arr)

[1 2 3 4 5]


In [72]:
arr.shape  #> (5,)

(5,)

In [73]:
result = arr[np.newaxis, :]
print(result)

[[1 2 3 4 5]]


In [74]:
result.shape  #> (1, 5)

(1, 5)

In [76]:
result = arr[:, np.newaxis]
print(result)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [77]:
result.shape  #> (5, 1)

(5, 1)

In [78]:
print(arr_2d)  #> shape: (3, 4)

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [79]:
result = arr_2d[np.newaxis, :, :]
print(result)

[[[123   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]]


In [80]:
result.shape  #> (1, 3, 4)

(1, 3, 4)

In [81]:
result = arr_2d[:, :, np.newaxis]
print(result)

[[[123]
  [  1]
  [  2]
  [  3]]

 [[  4]
  [  5]
  [  6]
  [  7]]

 [[  8]
  [  9]
  [ 10]
  [ 11]]]


In [82]:
result.shape  #> (3, 4, 1)

(3, 4, 1)

In [83]:
result = arr_2d[:, np.newaxis, :]
print(result)

[[[123   1   2   3]]

 [[  4   5   6   7]]

 [[  8   9  10  11]]]


In [84]:
result.shape

(3, 1, 4)

In [85]:
print(arr)

[1 2 3 4 5]


In [86]:
result = arr[:, np.newaxis, np.newaxis]
print(result)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]


In [87]:
result.shape

(5, 1, 1)

In [96]:
arr_2d

array([[123,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [106]:
arr_2d[np.newaxis, :]

array([[[123,   1,   2,   3]],

       [[  4,   5,   6,   7]],

       [[  8,   9,  10,  11]]])

# concatenate

*   `np.concatenate([array1, array2, ...], axis=0)`: 특정 축(axis) 방향으로 배열 이어붙이기.
*   `np.r_[array1, array2]`: 행들을 이어붙이기. axis=0 방향으로 이어붙이기.
*   `np.c_[array1, array2]`: 컬럼들을 이어붙이기. axis=1 방향으로 이어붙이기.

In [89]:
# (2, 3) shape의 2d array
arr1 = np.arange(1, 7).reshape((2, 3))
print(arr1)

[[1 2 3]
 [4 5 6]]


In [90]:
# (1, 3) shape의 2d array
arr2 = np.array([[7, 8, 9]])
print(arr2)

[[7 8 9]]


In [91]:
# (2, 1) shape의 2d array
arr3 = np.array([[10], [11]])
print(arr3)

[[10]
 [11]]


In [92]:
result = np.concatenate([arr1, arr2])  # axis=0 생략 가능(기본값)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
np.r_[arr1, arr2]  # arr1과 arr2가 2d array일 때 concatenate를 간단히.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
result = np.concatenate([arr1, arr3], axis=1)
print(result)

[[ 1  2  3 10]
 [ 4  5  6 11]]


In [95]:
np.c_[arr1, arr3]  # arr1과 arr3이 2d array일 때 concatenate를 간단히.

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

# Broadcasting

*   np.ndarray의 연산(+, -, *, /, //, %, >, <, ==, ...)은 같은 위치(인덱스)의 원소들끼리(elementwise) 연산이 수행됨.
*   서로 모양(shape)이 다른 배열들끼리 연산이 가능한 경우가 있음(broadcast가 가능한 경우)


In [107]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [108]:
print(a + b)

[5 7 9]


In [ ]:
c = np.array([7, 8])
# print(a + c)
#> ValueError: (3,) shape의 1d array와 (2,) shape의 1d array는 서로 연산을 할 수 없음.

## ndarray와 scalar의 연산

항상 broadcast가 가능. 항상 연산이 가능. 스칼라를 배열의 각 원소마다 연산 수행.

In [111]:
print(a + 10)

[11 12 13]


## 2d array와 1d array 또는 2d array에서의 broadcast

In [112]:
a = np.arange(1, 7).reshape((2, 3))  # shape: (2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [113]:
b = np.array([7, 8, 9])  # shape: (3,)
print(b)

[7 8 9]


In [114]:
# (3,) shape의 1d array -> (1, 3) shape 2d array -> (2, 3) shape으로 broadcast
print(a + b)

[[ 8 10 12]
 [11 13 15]]


In [115]:
b = np.array([[5], [10]])  # shape: (2, 1)
print(b)

[[ 5]
 [10]]


In [116]:
# (2, 1) shape의 2d array -> (2, 3) shape으로 broadcast
print(a + b)

[[ 6  7  8]
 [14 15 16]]


broadcasting이 가능한 경우:

*   브로드캐스팅은 누락되거나 길이가 1인 차원에 대해서만 수행.
*   이어지는 차원의 축이 길이가 같은 경우 브로드캐스팅이 가능.


## broadcast 활용

*   표준화(standardization): 배열의 평균이 0이 되고, 표준편차가 1이 되도록 값들을 변환.
*   정규화(normalization): 최솟값이 0이 되고 최댓값이 1이 되도록 값들을 변환.

### 표준화

In [120]:
x = np.array([1, 2, 3, 4, 5])

In [123]:
mu = x.mean()  # 평균, np.mean(x)
print(mu)

3.0


In [124]:
sigma = x.std()  # 표준편차, np.std(x)
print(sigma)

1.4142135623730951


In [125]:
x_scaled = (x - mu) / sigma
print(x_scaled)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [126]:
np.mean(x_scaled)

np.float64(0.0)

In [127]:
np.std(x_scaled)

np.float64(0.9999999999999999)

### 정규화

In [128]:
x_min = np.min(x)  # 배열 x의 최솟값
x_max = np.max(x)  # 배열 x의 최댓값
print(x_min, x_max)

1 5


In [129]:
x_scaled = (x - x_min) / (x_max - x_min)
print(x_scaled)

[0.   0.25 0.5  0.75 1.  ]


### 2차원 배열에서 표준화, 정규화

In [130]:
# (3, 2) shape 2d array
X = np.arange(1, 7).reshape((3, 2))
print(X)

[[1 2]
 [3 4]
 [5 6]]


In [133]:
# 표준화
X_scaled = (X - np.mean(X)) / np.std(X)
print(X_scaled)

[[-1.46385011 -0.87831007]
 [-0.29277002  0.29277002]
 [ 0.87831007  1.46385011]]


In [134]:
# 정규화
X_scaled = (X - np.min(X)) / (np.max(X) - np.min(X))
print(X_scaled)

[[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]
