<a href="https://colab.research.google.com/github/JakeOh/202505_BD50/blob/main/lab_da/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 고급기능

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# np.ndarray 속성

In [2]:
arr = np.ones(shape=(2, 3))

In [3]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr.shape  # shape 속성: 배열의 각 축(axis)을 따라서 있는 원소의 개수들의 tuple.

(2, 3)

In [5]:
arr.dtype  # dtype 속성: 배열 원소의 데이터 타입.

dtype('float64')

In [6]:
arr.size  # size 속성: 배열의 모든 원소 개수.

6

In [7]:
arr.ndim  # ndim: 배열의 차원(dimension). 배열의 축(axis)의 개수.

2

In [8]:
arr = np.arange(10)  # 0 이상 10 미만의 (10개의) 정수들로 이루어진 배열.

In [9]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print('dtyp:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtyp: int64
ndim: 1
shape: (10,)
size: 10


In [11]:
arr = np.arange(1, 25).reshape((2, 3, 4))

In [12]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
print('dtyp:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtyp: int64
ndim: 3
shape: (2, 3, 4)
size: 24


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [14]:
print(arr)  #> 3d array(3차원 배열)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [15]:
print(arr[0])  #> 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(arr[0, 0])  #> 1d array

[1 2 3 4]


In [17]:
print(arr[0][0])

[1 2 3 4]


In [18]:
print(arr[0, 0, 0])  #> int -> 스칼라(scalar)

1


In [19]:
print(arr[0][0][0])

1


*   Python list 인덱스 사용 방법:
    *   `list[i][j][k]...`
*   NumPy ndarray 인덱스 사용 방법:
    *   `array[i, j, k, ...]`
    *   `array[i][j][k]...`

# Slicing

## 1차원 배열의 slicing

In [20]:
np.random.seed(1)
arr = np.random.randint(100, size=10)  # [0, 100) 범위의 정수 난수 10개로 이루어진 1d array.

In [21]:
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [22]:
print(arr[1:5])

[12 72  9 75]


In [23]:
print(arr[:3])  #> 시작 인덱스 0은 생략 가능

[37 12 72]


In [24]:
print(arr[-3:])  #> 배열의 끝까지 자를 때는 마지막 인덱스는 생략 가능.
# 배열의 끝에서부터 거꾸로 매기는 인덱스는 음수 인덱스.

[64 16  1]


In [26]:
print(arr[0:1])  #> slicing의 결과 -> 배열
print(arr[0])    #> indexing의 결과 -> 원소(스칼라)

[37]
37


## 2차원 배열의 slicing

In [28]:
arr = np.arange(1, 21).reshape((4, 5))

In [29]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [35]:
# 2차원 배열 arr의 첫 2개의 1차원 배열
# print(arr[:2])
print(arr[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [36]:
# 2차원 배열 arr의 마지막 2개의 1차원 배열
# print(arr[-2:])
print(arr[-2:, :])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [38]:
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [41]:
print(arr[1:3][1:4])  # 위쪽 셀의 결과와 비교!

[[11 12 13 14 15]]


## 3차원 배열의 slicing

In [42]:
arr = np.arange(1, 61).reshape((3, 4, 5))

In [43]:
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [44]:
print(arr[:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [45]:
print(arr[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [47]:
# print(arr[:2, :2, :])
print(arr[:2, :2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [48]:
print(arr[:2, :2, :2])

[[[ 1  2]
  [ 6  7]]

 [[21 22]
  [26 27]]]


In [50]:
print(arr[:1, :, :])  #> 결과: 3d array

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [49]:
print(arr[0, :, :])  #> 결과: 2d array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
