<a href="https://colab.research.google.com/github/JakeOh/202505_BD50/blob/main/lab_da/ml04_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets  # load_iris() 함수 사용하기 위해서
from sklearn.model_selection import train_test_split  # 훈련 셋/테스트 셋 분리 함수
from sklearn.preprocessing import StandardScaler  # 특성 스케일링 클래스
from sklearn.neighbors import KNeighborsClassifier  # KNN 모델 클래스
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score  # 평가 지표

# Iris 데이터셋 준비

In [2]:
iris = datasets.load_iris()

In [4]:
print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>


scikit-learn Bunch 클래스: Python의 dict와 비슷한 클래스.
*   key-value 쌍으로 아이템들을 저장.
*   `bunch['key']` 또는 `bunch.key` 형식으로 key를 사용해서 value 값을 참조할 수 있음.

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
X = iris.data  # 특성 배열: (sample 개수, 특성 개수) shape을 갖는 2차원 배열(ndarray)

In [9]:
y = iris.target  # 타겟 배열: (sample 개수,) shape을 갖는 1차원 배열(ndarray)

In [11]:
X[:5, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [12]:
y[:5]

array([0, 0, 0, 0, 0])

In [13]:
np.unique(y, return_counts=True)  #> 레이블(타겟 클래스)들이 숫자로 인코딩되어 있음.

(array([0, 1, 2]), array([50, 50, 50]))

In [14]:
iris.target_names  #> 타겟 이름(문자열)

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
iris.feature_names  #> 특성 이름

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']