<a href="https://colab.research.google.com/github/JakeOh/202505_BD50/blob/main/lab_da/ml16_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network(인공 신경망)

# Imports

In [2]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_validate, train_test_split
from sklearn.metrics import accuracy_score

import tensorflow as tf
import keras

# Iris 데이터 셋

In [3]:
data, target = datasets.load_iris(return_X_y=True)

## 이진 분류

*   0(setosa)과 0이 아닌(versicolor, virginica) 클래스 분류 문제
*   2개의 특성만 사용.

In [4]:
X = data[:, :2]  # data에서 행은 모두 선택, 열은 첫 2개만 선택.
X.shape

(150, 2)

In [5]:
y = (target != 0).astype('int')
y  # 0 -> 0, 1 & 2 -> 1 변환.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## SGD Classifier

In [6]:
# Logistic 손실 함수를 최소화하는 확률적 경사 하강법 분류 모델을 생성.
# 최대 epoch(반복 횟수)를 10회로 설정.
sgd = SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [7]:
sgd.fit(X, y)  # SGD 모델 훈련
# 손실함수를 최소로 만들어주는 절편(intercept)과 계수들(coefficient)을 찾는 과정.

SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [8]:
sgd.intercept_

array([-53.41269101])

In [9]:
sgd.coef_

array([[ 107.47482122, -163.79917975]])

In [10]:
# 예측 확률
y_prob = sgd.predict_proba(X)  # 예측 확률

In [11]:
y_prob[:5]

array([[1.00000000e+00, 7.40567283e-35],
       [9.99999987e-01, 1.26753544e-08],
       [1.00000000e+00, 3.47056174e-32],
       [1.00000000e+00, 9.69472704e-30],
       [1.00000000e+00, 1.22541827e-46]])

In [12]:
y_pred = sgd.predict(X) # 예측 값
y_pred[:5]

array([0, 0, 0, 0, 0])

In [13]:
accuracy_score(y, y_pred)

0.9933333333333333

## 신경망(Neural Netwok)

In [14]:
inputs = keras.layers.Input(shape=(2,))  # 입력층(input layer)

In [15]:
dense = keras.layers.Dense(units=1, activation='sigmoid')  # 출력층(output layer)

In [16]:
model = keras.Sequential(layers=[inputs, dense])  # 신경망 모델 생성

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
# 신경망 모델 컴파일: optimizer(최적화 알고리즘), loss(손실함수), metrics(평가 기준)
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [19]:
# 신경망 모델 훈련
model.fit(x=X, y=y, batch_size=1, epochs=10)

Epoch 1/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.5214 - loss: 2.6805
Epoch 2/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.7720 - loss: 0.4305
Epoch 3/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8316 - loss: 0.4089
Epoch 4/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.8401 - loss: 0.3804
Epoch 5/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9364 - loss: 0.3521
Epoch 6/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.9715 - loss: 0.3260
Epoch 7/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9513 - loss: 0.2821
Epoch 8/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9743 - loss: 0.2686
Epoch 9/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.9554 - loss: 0.2594
Epoch 10/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.9666 - loss: 0.2538


In [20]:
# 신경망 모델 훈련을 통해서 찾은 파라미터들
model.weights

[<Variable path=sequential/dense/kernel, shape=(2, 1), dtype=float32, value=[[ 1.330629 ]
  [-2.1874192]]>,
 <Variable path=sequential/dense/bias, shape=(1,), dtype=float32, value=[0.02767001]>]

In [21]:
# 신경망 모델 평가
model.evaluate(x=X, y=y)  # evaluate 메서드는 5-fold 교차 검증을 수행.

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - binary_accuracy: 0.9791 - loss: 0.2906


[0.23084406554698944, 0.9866666793823242]

In [22]:
# 예측값 - 활성화 함수의 리턴값. 시그모이드 함수의 리턴값. 클래스(레이블)이 1이 될 확률.
y_pred = model.predict(X)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


In [23]:
y_pred.shape

(150, 1)

In [24]:
# 예측 레이블
y_pred_label = (y_pred > 0.5).astype('int').ravel()
y_pred_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 은닉층(hidden layer)을 가지고 있는 신경망

In [25]:
inputs = keras.layers.Input(shape=(2,))  # 입력층
dense1 = keras.layers.Dense(units=2, activation='sigmoid')  # 은닉층
dense2 = keras.layers.Dense(units=1, activation='sigmoid')  # 출력층

In [26]:
model = keras.Sequential(layers=[inputs, dense1, dense2])  # 신경망 생성

In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
# 모델 컴파일:
# 어떤 손실함수(loss)를 어떤 평가 기준(metrics)으로 어떻게 최적화(optimizer)할 것인 지를 설정
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [31]:
# 모델 훈련
model.fit(X, y, batch_size=1, epochs=1_000, verbose=0)

In [32]:
model.weights

[<Variable path=sequential_1/dense_1/kernel, shape=(2, 2), dtype=float32, value=[[-0.7664931  3.9437313]
  [-0.6238877 -5.2921705]]>,
 <Variable path=sequential_1/dense_1/bias, shape=(2,), dtype=float32, value=[-0.03823199 -5.2011485 ]>,
 <Variable path=sequential_1/dense_2/kernel, shape=(2, 1), dtype=float32, value=[[ 0.18851271]
  [11.617136  ]]>,
 <Variable path=sequential_1/dense_2/bias, shape=(1,), dtype=float32, value=[-5.751033]>]

In [33]:
y_pred = model.predict(X)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


In [34]:
y_pred_label = (y_pred > 0.5).astype('int').ravel()
y_pred_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
np.mean(y == y_pred_label)

np.float64(0.9933333333333333)