<a href="https://colab.research.google.com/github/JakeOh/202505_BD50/blob/main/lab_da/ml16_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network(인공 신경망)

# Imports

In [22]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_validate, train_test_split
from sklearn.metrics import accuracy_score

import tensorflow as tf
import keras

# Iris 데이터 셋

In [2]:
data, target = datasets.load_iris(return_X_y=True)

## 이진 분류

*   0(setosa)과 0이 아닌(versicolor, virginica) 클래스 분류 문제
*   2개의 특성만 사용.

In [8]:
X = data[:, :2]  # data에서 행은 모두 선택, 열은 첫 2개만 선택.
X.shape

(150, 2)

In [11]:
y = (target != 0).astype('int')
y  # 0 -> 0, 1 & 2 -> 1 변환.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## SGD Classifier

In [12]:
# Logistic 손실 함수를 최소화하는 확률적 경사 하강법 분류 모델을 생성.
# 최대 epoch(반복 횟수)를 10회로 설정.
sgd = SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [13]:
sgd.fit(X, y)  # SGD 모델 훈련
# 손실함수를 최소로 만들어주는 절편(intercept)과 계수들(coefficient)을 찾는 과정.

SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [14]:
sgd.intercept_

array([-53.41269101])

In [15]:
sgd.coef_

array([[ 107.47482122, -163.79917975]])

In [16]:
# 예측 확률
y_prob = sgd.predict_proba(X)  # 예측 확률

In [17]:
y_prob[:5]

array([[1.00000000e+00, 7.40567283e-35],
       [9.99999987e-01, 1.26753544e-08],
       [1.00000000e+00, 3.47056174e-32],
       [1.00000000e+00, 9.69472704e-30],
       [1.00000000e+00, 1.22541827e-46]])

In [18]:
y_pred = sgd.predict(X) # 예측 값
y_pred[:5]

array([0, 0, 0, 0, 0])

In [20]:
accuracy_score(y, y_pred)

0.9933333333333333

## 신경망(Neural Netwok)

In [23]:
inputs = keras.layers.Input(shape=(2,))  # 입력층(input layer)

In [24]:
dense = keras.layers.Dense(units=1, activation='sigmoid')  # 출력층(output layer)

In [25]:
model = keras.Sequential(layers=[inputs, dense])  # 신경망 모델 생성

In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
# 신경망 모델 컴파일: optimizer, loss, metrics
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [30]:
# 신경망 모델 훈련
model.fit(x=X, y=y, batch_size=1, epochs=10)

Epoch 1/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7821 - loss: 0.4592
Epoch 2/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.7698 - loss: 0.5200
Epoch 3/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.7930 - loss: 0.4399
Epoch 4/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8507 - loss: 0.4202
Epoch 5/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8581 - loss: 0.3755
Epoch 6/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9519 - loss: 0.3559
Epoch 7/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8927 - loss: 0.3160
Epoch 8/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9648 - loss: 0.3121
Epoch 9/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9559 - loss: 0.2589
Epoch 10/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9700 - loss: 0.2336


In [31]:
# 신경망 모델 훈련을 통해서 찾은 파라미터들
model.weights

[<Variable path=sequential/dense/kernel, shape=(2, 1), dtype=float32, value=[[ 1.1831506]
  [-2.0501866]]>,
 <Variable path=sequential/dense/bias, shape=(1,), dtype=float32, value=[-0.09582176]>]

In [34]:
# 신경망 모델 평가
model.evaluate(x=X, y=y)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.9921 - loss: 0.2745 


[0.2633025050163269, 0.9933333396911621]

In [35]:
# 예측값 - 활성화 함수의 리턴값. 시그모이드 함수의 리턴값. 1이 될 확률.
y_pred = model.predict(X)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


In [36]:
y_pred

array([[0.22488762],
       [0.38961196],
       [0.25056303],
       [0.2671937 ],
       [0.17354049],
       [0.1541343 ],
       [0.16465893],
       [0.2403606 ],
       [0.30248335],
       [0.34209728],
       [0.2154302 ],
       [0.19983384],
       [0.36186975],
       [0.23887919],
       [0.19243048],
       [0.08527946],
       [0.1541343 ],
       [0.22488762],
       [0.24184833],
       [0.135584  ],
       [0.33683228],
       [0.16145465],
       [0.11567908],
       [0.30420154],
       [0.19983384],
       [0.4180877 ],
       [0.2403606 ],
       [0.24617973],
       [0.286167  ],
       [0.25056303],
       [0.3159868 ],
       [0.33683228],
       [0.08712914],
       [0.09981545],
       [0.34209728],
       [0.32285857],
       [0.31774667],
       [0.15722059],
       [0.2610499 ],
       [0.26262125],
       [0.20493647],
       [0.6254923 ],
       [0.18991597],
       [0.20493647],
       [0.135584  ],
       [0.36186975],
       [0.135584  ],
       [0.229